### ISSUE TITLE
Local test

### ISSUE THREAD

**Issue by roarc0** [radiantmediaplayer/outstream-ads-gallery#1]
Hello! I'm trying to run this locally but I get this error:

```
rmp.min.js:9 InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at t.ha (rmp.min.js:9:605117)
    at Kn.ck (rmp.min.js:9:606183)
    at t.value (rmp.min.js:9:694318)
    at basic-with-reload.js:61:5 Stack table expanded"
```

**Comment by radiantmediaplayer** [comment]
Hi, sorry for the late reply, we missed that post. You need to have a license key for Radiant Media Player to use this (hence the atob error), Radiant Media Player is a paid HTML5 video player. If you want to give it a try you can request a free trial at https://www.radiantmediaplayer.com/free-trial.html.
If you want an open-source project to play outsream video advertsisement, have a look at rmp-vast: https://github.com/radiantmediaplayer/rmp-vast
